apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NadavBem/K8S_Jenkins_ArgoCD.git
    targetRevision: HEAD
    path: /guestbook/deployment.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default